#!/usr/bin/env bash
cd ~/catkin_ws
python3 -m pip install -e ./src/spot_ros/spot_wrapper/
rm -rf build devel
echo "#"
echo "#" catkin_make 1 of 3
echo "#"
sleep 1
catkin_make; 
echo "#"
echo "#" catkin_make 2 of 3
echo "#"
sleep 1
catkin_make; 
echo "#"
echo "#" catkin_make 3 of 3
echo "#"
sleep 1
catkin_make
. ./devel/setup.bash
cd -
python3 -m pip install transforms3d